### ISSUE TITLE
It is not compatible with Jest

### ISSUE THREAD

**Issue by jdiaz-nv** [CheeseGrinder/stencil-injection#1]
I tried to use this module with stenciljs and jest and it doesn't work

**Comment by Sukaato** [comment]
Hi,

Can you provide me an example so that I can reproduce the bug.

**Comment by Sukaato** [comment]
Hello
Without answer from you I close the ticket.

If the problem still persists you can always recreate a new ticket [here](https://github.com/CheeseGrinder/stencil-injection/issues/new/choose)
